### ISSUE TITLE
Chicago - Wrap up research assests

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#47]
@sabrinang Lets keep track of our to-do here.
Goal : Close Chicago research trip 

- [x] Participants profiles and notes - @LauraReynal
- [x] Admin - @LauraReynal
- [x] All post its must be transffered into a gdoc - @lauraReynal
- [x] Design workshop pictures uploaded + shared + observations- @LauraReynal @sabrinang 
- [x] Pictures from the trip uploaded on dropbox - @sabrinang 
- [x] Pictures from the trip uploaded on dropbox - @LauraReynal 
- [x] Pictures sent to each participants - @sabrinang 
- [x] Web Journey design tracking here #40 - @lovegushwa 
- [x] Web Journey Copy @LauraReynal
- [x] Threshold Diagram Copy @LauraReynal
- [x] Threshold Diagram design tracking here #3 - @lovegushwa 
- [x] Review report draft before we submit to team - @sabrinang 
- [x] Submit report for review to team - @LauraReynal 
- [x] Map the research on Mapbox - @LauraReynal 
- [x] Follow up with participants and partners - @LauraReynal 
- [x] Product feedback document and call - @LauraReynal  @sabrinang 
- [x] Skills : figure out what we do with them (small design or list )@LauraReynal @sabrinang 
- [x] Learning scenario - Review and design  tracking here #26 @lovegushwa 
- [x] A day in the life of a teen - Review and desgin @lovegushwa tracking here #48 
- [x] Change participants name for privacy @lauraReynal

Feel free to add what is missing :dancer: :microphone:

**Comment by sabrinang** [comment]
photos uploaded to Research/Chicago/Photos/Sabrina

**Comment by LauraReynal** [comment]
@sabrinang with the notes from the interview of K&J + The drawing I have, can we make a simple timeline for "A day in the life of a teenager in Chicago" ? will file a separate bug and add it to the list. 
Let me know what you think. It might be interesting for the persona.

**Comment by LauraReynal** [comment]
Also adding in the list that we need to anonymize all data and change names of participants for the reports. Will add new names on the "interview Tab" Feel free to suggest names too :)

**Comment by thisandagain** [comment]
Awesome. Thanks @LauraReynal :smile:

**Comment by sabrinang** [comment]
All the photos I taken on the trip are uploaded to gdrive (unedited): 5. Chicago Research > Chicago Photos > Sabrina 
https://drive.google.com/open?id=0B4Q8pzCpDS_efnJhSGxYY0tKRWt4cjZRcHlVQ1RUajN5ZFh2X2NiLXpvcjh6TDZUejJBek0&authuser=1

You can find edited photos of some participants in a separate folder: 5. Chicago Research > Chicago Photos > Sabrina > Edited Portraits
https://drive.google.com/open?id=0B4Q8pzCpDS_eflNuQURzdkQ4R2d1VVRfMUFaSXlYUXJ3TnRlNHJTRzhvWDMzWDlLZGVtdzQ&authuser=1

**Comment by LauraReynal** [comment]
Thanks @sabrinang . Will delete your old dropbox folder and add the participants portraits in dropbox for @lovegushwa

**Comment by LauraReynal** [comment]
@sabrinang I changed names of everyone and updated the PPF tab and the notes tab -- so if you ever need to quote or use things, make sure its the fake name :sunglasses: 
Thanks
