### ISSUE TITLE
TODO List after Indonesia + NYC Research

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/research#73]
#### Teach Product Report
- [ ] Summarize findings for teach website

#### Community Report
- [ ] Make vector image for Hive+Community Venn diagram
- [ ] Summarize findings specific to Indonesia culture/community
- [ ] Summarize findings specific to NYC and Hive

**Comment by secretrobotron** [comment]
- [ ] Make vector image for "finger" breakdown

**Comment by secretrobotron** [comment]
- [ ] Draw "finger" breakdown and upload here

**Comment by secretrobotron** [comment]
- [ ] Upload latest Venn diagram here (from @LauraReynal's notebook)

**Comment by LauraReynal** [comment]
YUP

**Comment by LauraReynal** [comment]
Finish participants profile spreadsheet

**Comment by LauraReynal** [comment]
Triage photos and videos

**Comment by LauraReynal** [comment]
Send thank you note to participants

**Comment by secretrobotron** [comment]
- [ ] Finish participants profile spreadsheet
- [ ] Triage photos and videos
- [ ] Send thank you note to participants

**Comment by LauraReynal** [comment]
- [ ] type the postits

**Comment by LauraReynal** [comment]
first iteration - this was made to be quick, but we should do a better one 
![hive and contributors venn diagram - new page](https://cloud.githubusercontent.com/assets/8261945/10817196/a0841cee-7e38-11e5-8c9f-8ce216e0c1fe.png)

**Comment by LauraReynal** [comment]
@secretrobotron can you provide critic on this new version below ? Thanks :cactus: :cat: :bouquet: 
![hive and contributors venn diagram - new page](https://cloud.githubusercontent.com/assets/8261945/10845570/3a7a257a-7f09-11e5-99b5-faa1158d4e9a.png)

**Comment by secretrobotron** [comment]
> Mozilla encourages existing organizations and programs to teach the web using our tools, which often creates a tension.

I don't know that there's a real tension. Maybe this:

"Mozilla helps manage the network. Constituent orgs do not feel compelled to participate in web literacy programs or tools."

**Comment by secretrobotron** [comment]
Those circles look a bit misaligned.

**Comment by secretrobotron** [comment]
Maybe there are a couple of questions to ask about the intersections instead of the big orange arrow at the top:
* Intersection between Hive & Contributors: How can the two networks provide value to each other?
* Middle intersection: What [programs/products] do these groups need to sustain/grow their relationship?
* Intersection between Hive & Software: What does this network need to maintain or improve the communication it already finds useful (think about disappearance of minigroup)?
* Intersection between Contributors & Software: What does this network need to continue their work effectively? Integration with existing Moz community platforms? Better, more adaptable content and instructions for events?

**Comment by secretrobotron** [comment]
> Their common point is us, the mission, the web.

"Their common point is Mozilla: the mission, the web."

**Comment by secretrobotron** [comment]
> Mozilla encourages individuals to join a global learning movement. People join for us. There is less tension.

"Mozilla encourages individuals to join a global learning movement. They join to support Mozilla. Readily accept web literacy programs/tools."

**Comment by secretrobotron** [comment]
For the two top circles' descriptions:

> Their common point...

"Their common focus..."

**Comment by secretrobotron** [comment]
:jack_o_lantern: :japanese_goblin: :whale2:

**Comment by LauraReynal** [comment]
:flags: :flashlight: :flushed:

**Comment by secretrobotron** [comment]
![venn diagram 2](https://cloud.githubusercontent.com/assets/403231/10848436/4288e7fe-7ef2-11e5-92d9-99705b60a845.jpg)

**Comment by LauraReynal** [comment]
WOW 
that is beautiful
